apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: "${app_name:=demo}-app"
  labels:
    app.kubernetes.io/part-of: "${app_name:=demo}"
  annotations:
    app.kubernetes.io/owner: "${app_name:=demo}-team"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "${app_name:=demo}-app"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 98
