---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-client
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./client
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-client
      #qps: "1"
