---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-frontend
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./microservice
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-frontend
  patches:
    - target:
        kind: Deployment
        labelSelector: "app.kubernetes.io/component=app"
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/command/-
          value: --backend-url=http://demo-auth-app/echo
        - op: add
          path: /spec/template/spec/containers/0/command/-
          value: --backend-url=http://demo-cart-app/echo
        - op: add
          path: /spec/template/spec/containers/0/command/-
          value: --backend-url=http://demo-catalogue-app/echo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-cart
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./microservice
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-cart
  patches:
    - target:
        kind: Deployment
        labelSelector: "app.kubernetes.io/component=app"
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/command/-
          value: --backend-url=http://demo-checkout-app/echo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-checkout
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./microservice
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-checkout
  patches:
    - target:
        kind: Deployment
        labelSelector: "app.kubernetes.io/component=app"
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/command/-
          value: --backend-url=http://demo-shipping-app/echo
        - op: add
          path: /spec/template/spec/containers/0/command/-
          value: --backend-url=http://demo-payment-app/echo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-advert
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./microservice
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-advert
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-payment
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./microservice
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-payment
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-catalogue
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./microservice
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-catalogue
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-shipping
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./microservice
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-shipping
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-auth
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./microservice
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-mobile
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./microservice
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-mobile
  patches:
    - target:
        kind: Deployment
        labelSelector: "app.kubernetes.io/component=app"
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/command/-
          value: --backend-url=http://demo-auth-app/echo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-admin
  namespace: "${app_namespace:=msdemo}"
spec:
  targetNamespace: "${app_namespace:=msdemo}"
  interval: 60m0s
  retryInterval: 1m30s
  path: ./microservice
  prune: true
  wait: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: "${app_namespace:=msdemo}"
  postBuild:
    substitute:
      app_name: demo-admin
  patches:
    - target:
        kind: Deployment
        labelSelector: "app.kubernetes.io/component=app"
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/command/-
          value: --backend-url=http://demo-auth-app/echo
